name: CI

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  release:
    types:
      - published

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_REPOSITORY: bgruening/galaxy-ngs-preprocessing

jobs:
  build:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image (no push)
        uses: bgruening/docker-galaxy-github-action@main
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          tags: ci-${{ github.sha }}
          tool-file: ngs_preprocessing.yml
          base-image: quay.io/bgruening/galaxy:25.1.1
          push: false

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: quay.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push image
        uses: bgruening/docker-galaxy-github-action@main
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          push: true
          tool-file: ngs_preprocessing.yml
          base-image: quay.io/bgruening/galaxy:25.1.1
          username: '$oauthtoken'
          password: ${{ secrets.QUAY_OAUTH_TOKEN }}
          tags: |
            ${{ github.event.release.tag_name }}
            latest
